title:             Based Solutions
email:             mrgofuckyourself@pm.me
description:       Silent Observations and long nights coding
author:            WebMaster Exit 1
#url:               "localhost:4000"
url:               "http://based-solutions.github.io/"
baseurl:

# Social Profiles
#twitter_username:  SBootstrap
github_username:   Webmaster-exit-1
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate



description: >- # this means to ignore newlines until "baseurl:"
  A website to display my repositories.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://based-solutions.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  webmaster-exit-1

# Build settings
theme: jekyll-theme-awesome
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
